[build.environment]
PYTHON_VERSION = "3.11.5"  # Replace with the latest stable Python version

[build]
  functions = "functions"
  publish = "static"
  command = "pip install -r requirements.txt"

[functions]
  directory = "functions"
