[build.environment]
PYTHON_VERSION = "3.9.9"  # Update to a valid version

[build]
  functions = "functions"
  publish = "static"
  command = "pip install -r requirements.txt"

[functions]
  directory = "functions"
  
